# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='value_type',
            field=models.CharField(choices=[('string', '\u5b57\u7b26\u4e32'), ('number', '\u6570\u5b57'), ('list', '\u5217\u8868'), ('json', 'json'), ('datetime', '\u65e5\u671f\u65f6\u95f4')], default='string', max_length=16),
        ),
    ]
