# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('access_key', models.CharField(max_length=128)),
                ('access_secret', models.CharField(max_length=128)),
                ('inner_url', models.URLField(blank=True, verbose_name='inner url')),
                ('outer_url', models.URLField(blank=True, verbose_name='outer url')),
            ],
        ),
    ]
