# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='status',
            field=models.BooleanField(choices=[(True, '\u542f\u7528'), (False, '\u7981\u7528')], default=True),
        ),
    ]
