# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0002_bucket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('save_to_disk', models.BooleanField(default=True)),
                ('file_path', models.FilePathField(blank=models.BooleanField(default=True))),
            ],
        ),
        migrations.AlterField(
            model_name='bucket',
            name='inner_url',
            field=models.URLField(blank=True, verbose_name='inner base url'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='outer_url',
            field=models.URLField(blank=True, verbose_name='outer base url'),
        ),
    ]
