# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycronjob', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCron_Job',
            new_name='Job',
        ),
    ]
