# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycronjob', '0002_auto_20171201_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_run_time',
            field=models.DateTimeField(null=True, verbose_name='last run time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='next_run_time',
            field=models.DateTimeField(null=True, verbose_name='next run time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start time'),
        ),
    ]
